spring:

  thymeleaf:
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://47.100.243.106:3306/xfsjk?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: hapadmin
    password: hapadmin123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: mapper/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql