package com.example.demo.mapper;

import com.example.demo.model.FceLocalinfo;
import com.example.demo.model.FceLocalinfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FceLocalinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int countByExample(FceLocalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int deleteByExample(FceLocalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int insert(FceLocalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int insertSelective(FceLocalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    List<FceLocalinfo> selectByExampleWithBLOBs(FceLocalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    List<FceLocalinfo> selectByExample(FceLocalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    FceLocalinfo selectByPrimaryKey(Long id);
    public List<FceLocalinfo> selectByPrimaryKey2();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FceLocalinfo record, @Param("example") FceLocalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") FceLocalinfo record, @Param("example") FceLocalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FceLocalinfo record, @Param("example") FceLocalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FceLocalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(FceLocalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fce_localinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FceLocalinfo record);
}