package com.example.demo.model;

import java.util.Date;

public class FceLocalinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fce_localinfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fce_localinfo.locainfo
     *
     * @mbggenerated
     */
    private String locainfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fce_localinfo.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fce_localinfo.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fce_localinfo.port
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fce_localinfo.original_info
     *
     * @mbggenerated
     */
    private byte[] originalInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fce_localinfo.id
     *
     * @return the value of fce_localinfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fce_localinfo.id
     *
     * @param id the value for fce_localinfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fce_localinfo.locainfo
     *
     * @return the value of fce_localinfo.locainfo
     *
     * @mbggenerated
     */
    public String getLocainfo() {
        return locainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fce_localinfo.locainfo
     *
     * @param locainfo the value for fce_localinfo.locainfo
     *
     * @mbggenerated
     */
    public void setLocainfo(String locainfo) {
        this.locainfo = locainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fce_localinfo.createdate
     *
     * @return the value of fce_localinfo.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fce_localinfo.createdate
     *
     * @param createdate the value for fce_localinfo.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fce_localinfo.address
     *
     * @return the value of fce_localinfo.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fce_localinfo.address
     *
     * @param address the value for fce_localinfo.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fce_localinfo.port
     *
     * @return the value of fce_localinfo.port
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fce_localinfo.port
     *
     * @param port the value for fce_localinfo.port
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fce_localinfo.original_info
     *
     * @return the value of fce_localinfo.original_info
     *
     * @mbggenerated
     */
    public byte[] getOriginalInfo() {
        return originalInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fce_localinfo.original_info
     *
     * @param originalInfo the value for fce_localinfo.original_info
     *
     * @mbggenerated
     */
    public void setOriginalInfo(byte[] originalInfo) {
        this.originalInfo = originalInfo;
    }
}